<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lukas Beinhauer">

<title>Results Reliability Generalization and Variance Decomposition</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Results_files/libs/clipboard/clipboard.min.js"></script>
<script src="Results_files/libs/quarto-html/quarto.js"></script>
<script src="Results_files/libs/quarto-html/popper.min.js"></script>
<script src="Results_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Results_files/libs/quarto-html/anchor.min.js"></script>
<link href="Results_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Results_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Results_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Results_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Results_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Results Reliability Generalization and Variance Decomposition</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lukas Beinhauer </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>paths_rel <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="fu">file.path</span>(<span class="st">"Data/Reliability Estimates"</span>), <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>paths_alpha <span class="ot">&lt;-</span> paths_rel[<span class="fu">grep</span>(<span class="st">"_Alpha.csv$"</span>, paths_rel)]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>alpha_estimates.list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(paths_alpha, <span class="at">FUN =</span> <span class="cf">function</span>(x){<span class="fu">read.csv</span>(x)})</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>Alpha_rma.list <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"Data/Shiny Data/Alpha_rma.list.RData"</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>Bonett.Alpha_rma.list <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"Data/Shiny Data/Bonett.Alpha_rma.list.RData"</span>))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>varT_est.list <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"Notes/bootstrapped_varT.RData"</span>))</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>varE_est.list <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"Notes/bootstrapped_varE.RData"</span>))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>varT_rma.list <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"Notes/bootstrapped_varT_rma.RData"</span>))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>varE_rma.list <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">file.path</span>(<span class="st">"Notes/bootstrapped_varE_rma.RData"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>s_Caciop_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">1</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>r.dec <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>s_Caciop_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">1</span>]]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>s_Caciop_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">1</span>]]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>s_Caciop_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">1</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>s_Caciop_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">1</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>s_Caciop_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">1</span>]]</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>s_Caciop_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">1</span>]]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>s_ShnabelRPP_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">9</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>s_ShnabelRPP_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">9</span>]]</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>s_ShnabelRPP_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">9</span>]]</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>s_ShnabelRPP_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">9</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>s_ShnabelRPP_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">9</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>s_ShnabelRPP_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">9</span>]]</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>s_ShnabelRPP_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">9</span>]]</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>s_ShnabelRev_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">8</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>s_ShnabelRev_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">8</span>]]</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>s_ShnabelRev_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">8</span>]]</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>s_ShnabelRev_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">8</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>s_ShnabelRev_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">8</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>s_ShnabelRev_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">8</span>]]</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>s_ShnabelRev_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">8</span>]]</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>s_HexHH_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">6</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>s_HexHH_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">6</span>]]</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>s_HexHH_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">6</span>]]</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>s_HexHH_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">6</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>s_HexHH_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">6</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>s_HexHH_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">6</span>]]</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>s_HexHH_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">6</span>]]</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>s_HexEM_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">4</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>s_HexEM_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">4</span>]]</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>s_HexEM_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">4</span>]]</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>s_HexEM_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">4</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>s_HexEM_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">4</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>s_HexEM_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">4</span>]]</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>s_HexEM_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">4</span>]]</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>s_HexEX_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">5</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>s_HexEX_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">5</span>]]</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>s_HexEX_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">5</span>]]</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>s_HexEX_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">5</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>s_HexEX_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">5</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a>s_HexEX_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">5</span>]]</span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>s_HexEX_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">5</span>]]</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a>s_HexAG_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">2</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a>s_HexAG_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">2</span>]]</span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a>s_HexAG_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">2</span>]]</span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a>s_HexAG_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">2</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a>s_HexAG_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">2</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a>s_HexAG_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">2</span>]]</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a>s_HexAG_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">2</span>]]</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a>s_HexCO_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">3</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a>s_HexCO_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">3</span>]]</span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a>s_HexCO_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">3</span>]]</span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a>s_HexCO_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">3</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a>s_HexCO_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">3</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a>s_HexCO_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">3</span>]]</span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a>s_HexCO_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">3</span>]]</span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a>s_HexOX_Alpha <span class="ot">&lt;-</span> <span class="fu">summary</span>(alpha_estimates.list[[<span class="dv">7</span>]]<span class="sc">$</span>Reliability)</span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a>s_HexOX_Alpha_rma <span class="ot">&lt;-</span> Alpha_rma.list[[<span class="dv">7</span>]]</span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a>s_HexOX_B.Alpha_rma <span class="ot">&lt;-</span> Bonett.Alpha_rma.list[[<span class="dv">7</span>]]</span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a>s_HexOX_varT <span class="ot">&lt;-</span> <span class="fu">summary</span>(varT_est.list[[<span class="dv">7</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a>s_HexOX_varE <span class="ot">&lt;-</span> <span class="fu">summary</span>(varE_est.list[[<span class="dv">7</span>]]<span class="sc">$</span>var.est)</span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a>s_HexOX_varT_rma <span class="ot">&lt;-</span> varT_rma.list[[<span class="dv">7</span>]]</span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a>s_HexOX_varE_rma <span class="ot">&lt;-</span> varE_rma.list[[<span class="dv">7</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="results-reliability-generalization-and-variance-decomposition" class="level2">
<h2 class="anchored" data-anchor-id="results-reliability-generalization-and-variance-decomposition">Results Reliability Generalization and Variance Decomposition</h2>
<section id="cacioppo" class="level3">
<h3 class="anchored" data-anchor-id="cacioppo">Cacioppo</h3>
<p>Data set 1 concerned the scale of Need for Cognition (Cacioppo &amp; Petty, 1982), consisting of 6 Likert-stye items (5-point scale). Measured across 21 labs in Ebersole et al.&nbsp;(2016), using Cronbach’s Alpha, score reliability varied between 0.406 and 0.819, with a mean value of 0.586 and median value 0.578. Performing a random-effects meta-analysis on the untransformed Cronbach’s Alpha estimates, we find a meta-analytic mean estimate of 0.601 (0.558 : 0.644). Additionally, we find a significant degree of heterogeneity in score reliability, at Q(20) = 192.728, p &lt;.001. In terms of I^2, heterogeneity is 77.075%, which, according to XXX constitutes a large level of heterogeneity. In terms of tau, we find a standard deviation of 0.082 in true values of Cronbach’s Alpha. Similarly, when assessing Bonett-transformed Cronbach’s Alpha estimates, we find a meta-analytic mean of -0.906. Back-transformed this constitutes a Cronbach’s Alpha of 0.596 (CI: 0.549 : 0.638) (difference in MA-est. emerges at the 3rd decimal). Heterogeneity in Bonett-transformed estimates of Cronbach’s Alpha is also of statistically significant degree: Q(20) = 80.554, p &lt;.001. Standardized heterogeneity estimates of I^2 = 77.298% and H^2 = 4.405 display highly similar amounts of heterogeneity. When using McDonald’s Omega to estimate score reliability, the results change only to a very small degree. Therefore, estimates using McDonald’s Omega can be found in the supplemental materials.</p>
<p>Also, we use Cronbach’s Alpha to decompose the observed variance into its true and error score variance components:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>{}</th>
<th>True Score Variance</th>
<th style="text-align: right;">Error Score Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Min</td>
<td>0.101</td>
<td style="text-align: right;">0.111</td>
</tr>
<tr class="even">
<td>Q1</td>
<td>0.153</td>
<td style="text-align: right;">0.126</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>0.169</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="even">
<td>Q3</td>
<td>0.203</td>
<td style="text-align: right;">0.131</td>
</tr>
<tr class="odd">
<td>Max</td>
<td>0.238</td>
<td style="text-align: right;">0.134</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>0.555</td>
<td style="text-align: right;">0.15</td>
</tr>
</tbody>
</table>
<p>Performing a random-effects meta-analysis on the components directly leads to:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>{}</th>
<th>True Score Variance</th>
<th style="text-align: right;">Error Score Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meta-Analytic Mean Estimate</td>
<td>0.201</td>
<td style="text-align: right;">0.127</td>
</tr>
<tr class="even">
<td>Confidence Interval</td>
<td>0.159 : 0.243</td>
<td style="text-align: right;">0.124 : 0.131</td>
</tr>
<tr class="odd">
<td>Heterogeneity tau</td>
<td>0.089</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td>Heterogeneity I^2</td>
<td>83.888</td>
<td style="text-align: right;">9.444</td>
</tr>
<tr class="odd">
<td>Heterogeneity H^2</td>
<td>6.206</td>
<td style="text-align: right;">1.104</td>
</tr>
<tr class="even">
<td>Q(20)</td>
<td>129.574</td>
<td style="text-align: right;">22.735</td>
</tr>
<tr class="odd">
<td>p-value QE</td>
<td>&lt;.001</td>
<td style="text-align: right;">0.302</td>
</tr>
</tbody>
</table>
</section>
<section id="shnabel-sense-of-power-rpp" class="level3">
<h3 class="anchored" data-anchor-id="shnabel-sense-of-power-rpp">Shnabel Sense of Power (RPP)</h3>
<p>Data set 2 concerned the scale of Sense of Power (Shnabel &amp; Nadler, 2008), consisting of 3 Likert-stye items (7-point scale). Measured across 8 labs in Baranski et al.&nbsp;(2020), using Cronbach’s Alpha, specifically for those labs following the RPP-protocol, score reliability varied between 0.723 and 0.828, with a mean value of 0.763 and median value 0.752. Performing a random-effects meta-analysis on the untransformed Cronbach’s Alpha estimates, we find a meta-analytic mean estimate of 0.769 (0.739 : 0.799). Additionally, we find a significant degree of heterogeneity in score reliability, at Q(7) = 15.851, p = 0.027. In terms of I^2, heterogeneity is 55.557%, which, according to XXX constitutes a medium level of heterogeneity. In terms of tau, we find a standard deviation of 0.031 in true values of Cronbach’s Alpha. Similarly, when assessing Bonett-transformed Cronbach’s Alpha estimates, we find a meta-analytic mean of -1.458. Back-transformed this constitutes a Cronbach’s Alpha of 0.767 (CI: 0.736 : 0.795) (difference in MA-est. emerges at the 3rd decimal). Heterogeneity in Bonett-transformed estimates of Cronbach’s Alpha is also of statistically significant degree: Q(7) = 16.013, p = 0.025. Standardized heterogeneity estimates of I^2 = 56.122% and H^2 = 2.279 display highly similar amounts of heterogeneity.</p>
<p>Also, we use Cronbach’s Alpha to decompose the observed variance into its true and error score variance components:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>{}</th>
<th>True Score Variance</th>
<th style="text-align: right;">Error Score Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Min</td>
<td>0.67</td>
<td style="text-align: right;">0.204</td>
</tr>
<tr class="even">
<td>Q1</td>
<td>0.755</td>
<td style="text-align: right;">0.256</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>0.81</td>
<td style="text-align: right;">0.263</td>
</tr>
<tr class="even">
<td>Q3</td>
<td>0.864</td>
<td style="text-align: right;">0.262</td>
</tr>
<tr class="odd">
<td>Max</td>
<td>0.935</td>
<td style="text-align: right;">0.277</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>1.236</td>
<td style="text-align: right;">0.296</td>
</tr>
</tbody>
</table>
<p>Performing a random-effects meta-analysis on the components directly leads to:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>{}</th>
<th>True Score Variance</th>
<th style="text-align: right;">Error Score Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meta-Analytic Mean Estimate</td>
<td>0.829</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td>Confidence Interval</td>
<td>0.726 : 0.931</td>
<td style="text-align: right;">0.238 : 0.281</td>
</tr>
<tr class="odd">
<td>Heterogeneity tau</td>
<td>0.063</td>
<td style="text-align: right;">0.025</td>
</tr>
<tr class="even">
<td>Heterogeneity I^2</td>
<td>18.662</td>
<td style="text-align: right;">66.311</td>
</tr>
<tr class="odd">
<td>Heterogeneity H^2</td>
<td>1.229</td>
<td style="text-align: right;">2.968</td>
</tr>
<tr class="even">
<td>Q(7)</td>
<td>9.723</td>
<td style="text-align: right;">24.052</td>
</tr>
<tr class="odd">
<td>p-value QE</td>
<td>0.205</td>
<td style="text-align: right;">0.001</td>
</tr>
</tbody>
</table>
</section>
<section id="shnabel-sense-of-power-rev" class="level3">
<h3 class="anchored" data-anchor-id="shnabel-sense-of-power-rev">Shnabel Sense of Power (Rev)</h3>
<p>Comparing those results to the labs employing the revised protocol, score reliability varied between 0.603 and 0.757, with a mean value of 0.696 and median value 0.701. Performing a random-effects meta-analysis on the untransformed Cronbach’s Alpha estimates, we find a meta-analytic mean estimate of 0.706 (0.672 : 0.74). Additionally, we find no significant degree of heterogeneity in score reliability, at Q(7) = 13.045, p = 0.071. In terms of I^2, heterogeneity is 47.571%, which, according to XXX constitutes a low to medium level of heterogeneity. In terms of tau, we find a standard deviation of 0.033 in true values of Cronbach’s Alpha. Similarly, when assessing Bonett-transformed Cronbach’s Alpha estimates, we find a meta-analytic mean of -1.209. Back-transformed this constitutes a Cronbach’s Alpha of 0.701 (CI: 0.663 : 0.736) (difference in MA-est. emerges at the 3rd decimal). Heterogeneity in Bonett-transformed estimates of Cronbach’s Alpha is of statistically significant degree: Q(7) = 14.839, p = 0.038. Standardized heterogeneity estimates of I^2 = 53.705% and H^2 = 2.16 display highly similar amounts of heterogeneity.</p>
<p>Also, we use Cronbach’s Alpha to decompose the observed variance into its true and error score variance components:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>{}</th>
<th>True Score Variance</th>
<th style="text-align: right;">Error Score Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Min</td>
<td>0.541</td>
<td style="text-align: right;">0.231</td>
</tr>
<tr class="even">
<td>Q1</td>
<td>0.604</td>
<td style="text-align: right;">0.289</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>0.679</td>
<td style="text-align: right;">0.304</td>
</tr>
<tr class="even">
<td>Q3</td>
<td>0.705</td>
<td style="text-align: right;">0.301</td>
</tr>
<tr class="odd">
<td>Max</td>
<td>0.821</td>
<td style="text-align: right;">0.322</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>0.914</td>
<td style="text-align: right;">0.355</td>
</tr>
</tbody>
</table>
<p>Performing a random-effects meta-analysis on the components directly leads to:</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>{}</th>
<th>True Score Variance</th>
<th style="text-align: right;">Error Score Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meta-Analytic Mean Estimate</td>
<td>0.689</td>
<td style="text-align: right;">0.299</td>
</tr>
<tr class="even">
<td>Confidence Interval</td>
<td>0.584 : 0.794</td>
<td style="text-align: right;">0.27 : 0.328</td>
</tr>
<tr class="odd">
<td>Heterogeneity tau</td>
<td>0.101</td>
<td style="text-align: right;">0.036</td>
</tr>
<tr class="even">
<td>Heterogeneity I^2</td>
<td>45.728</td>
<td style="text-align: right;">75.265</td>
</tr>
<tr class="odd">
<td>Heterogeneity H^2</td>
<td>1.843</td>
<td style="text-align: right;">4.043</td>
</tr>
<tr class="even">
<td>Q(7)</td>
<td>12.528</td>
<td style="text-align: right;">36.801</td>
</tr>
<tr class="odd">
<td>p-value QE</td>
<td>0.084</td>
<td style="text-align: right;">&lt;.001</td>
</tr>
</tbody>
</table>
</section>
<section id="hexaco" class="level3">
<h3 class="anchored" data-anchor-id="hexaco">HEXACO</h3>
<section id="cronbachs-alpha" class="level4">
<h4 class="anchored" data-anchor-id="cronbachs-alpha">Cronbach’s Alpha</h4>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>HH</th>
<th>EM</th>
<th>EX</th>
<th>AG</th>
<th style="text-align: right;">CO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meta-analytic mean estimate</td>
<td>0.706</td>
<td>0.767</td>
<td>0.798</td>
<td>0.735</td>
<td style="text-align: right;">0.756</td>
</tr>
<tr class="even">
<td>Confidence Interval</td>
<td>0.68 : 0.731</td>
<td>0.746 : 0.788</td>
<td>0.773 : 0.822</td>
<td>0.712 : 0.758</td>
<td style="text-align: right;">0.727 : 0.785</td>
</tr>
<tr class="odd">
<td>Heterogeneity tau</td>
<td>0.039</td>
<td>0.033</td>
<td>0.046</td>
<td>0.036</td>
<td style="text-align: right;">0.054</td>
</tr>
<tr class="even">
<td>Heteroeneity I^2</td>
<td>50.048</td>
<td>52.721</td>
<td>75.37</td>
<td>50.528</td>
<td style="text-align: right;">75.125</td>
</tr>
<tr class="odd">
<td>Heterogeneity H^2</td>
<td>2.002</td>
<td>2.115</td>
<td>4.06</td>
<td>2.021</td>
<td style="text-align: right;">4.02</td>
</tr>
<tr class="even">
<td>Q(18)</td>
<td>39.346</td>
<td>44.673</td>
<td>64.587</td>
<td>44.159</td>
<td style="text-align: right;">57.724</td>
</tr>
<tr class="odd">
<td>P-value QE</td>
<td>0.003</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td style="text-align: right;">&lt;.001</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>HH</th>
<th>EM</th>
<th>EX</th>
<th>AG</th>
<th style="text-align: right;">CO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Min</td>
<td>0.433</td>
<td>0.461</td>
<td>0.65</td>
<td>0.377</td>
<td style="text-align: right;">0.521</td>
</tr>
<tr class="even">
<td>Q1</td>
<td>0.662</td>
<td>0.745</td>
<td>0.75</td>
<td>0.709</td>
<td style="text-align: right;">0.701</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>0.715</td>
<td>0.763</td>
<td>0.803</td>
<td>0.739</td>
<td style="text-align: right;">0.784</td>
</tr>
<tr class="even">
<td>Q3</td>
<td>0.689</td>
<td>0.75</td>
<td>0.788</td>
<td>0.716</td>
<td style="text-align: right;">0.741</td>
</tr>
<tr class="odd">
<td>Max</td>
<td>0.745</td>
<td>0.803</td>
<td>0.836</td>
<td>0.763</td>
<td style="text-align: right;">0.796</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>0.773</td>
<td>0.826</td>
<td>0.879</td>
<td>0.801</td>
<td style="text-align: right;">0.826</td>
</tr>
</tbody>
</table>
<section id="back-transformed-bonett-estimates-meta-analytic-results" class="level5">
<h5 class="anchored" data-anchor-id="back-transformed-bonett-estimates-meta-analytic-results">Back-transformed Bonett-estimates (meta-analytic results)</h5>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>HH</th>
<th>EM</th>
<th>EX</th>
<th>AG</th>
<th style="text-align: right;">CO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meta-analytic mean estimate</td>
<td>0.696</td>
<td>0.759</td>
<td>0.796</td>
<td>0.726</td>
<td style="text-align: right;">0.751</td>
</tr>
<tr class="even">
<td>Confidence Interval</td>
<td>0.663 : 0.726</td>
<td>0.729 : 0.786</td>
<td>0.769 : 0.82</td>
<td>0.692 : 0.757</td>
<td style="text-align: right;">0.717 : 0.782</td>
</tr>
<tr class="odd">
<td>Heteroeneity I^2</td>
<td>66.793</td>
<td>74.745</td>
<td>77.198</td>
<td>73.843</td>
<td style="text-align: right;">78.945</td>
</tr>
<tr class="even">
<td>Heterogeneity H^2</td>
<td>3.011</td>
<td>3.96</td>
<td>4.386</td>
<td>3.823</td>
<td style="text-align: right;">4.75</td>
</tr>
<tr class="odd">
<td>Q(18)</td>
<td>55.265</td>
<td>74.094</td>
<td>78.648</td>
<td>69.962</td>
<td style="text-align: right;">90.827</td>
</tr>
<tr class="even">
<td>P-value QE</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td style="text-align: right;">&lt;.001</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="true-score-variance" class="level4">
<h4 class="anchored" data-anchor-id="true-score-variance">True Score Variance</h4>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>HH</th>
<th>EM</th>
<th>EX</th>
<th>AG</th>
<th style="text-align: right;">CO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Min</td>
<td>0.077</td>
<td>0.086</td>
<td>0.144</td>
<td>0.052</td>
<td style="text-align: right;">0.102</td>
</tr>
<tr class="even">
<td>Q1</td>
<td>0.204</td>
<td>0.287</td>
<td>0.272</td>
<td>0.239</td>
<td style="text-align: right;">0.219</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>0.258</td>
<td>0.319</td>
<td>0.307</td>
<td>0.256</td>
<td style="text-align: right;">0.268</td>
</tr>
<tr class="even">
<td>Q3</td>
<td>0.241</td>
<td>0.318</td>
<td>0.337</td>
<td>0.253</td>
<td style="text-align: right;">0.268</td>
</tr>
<tr class="odd">
<td>Max</td>
<td>0.279</td>
<td>0.391</td>
<td>0.409</td>
<td>0.292</td>
<td style="text-align: right;">0.326</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>0.336</td>
<td>0.44</td>
<td>0.525</td>
<td>0.383</td>
<td style="text-align: right;">0.43</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>HH</th>
<th>EM</th>
<th>EX</th>
<th>AG</th>
<th style="text-align: right;">CO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meta-analytic mean estimate</td>
<td>0.235</td>
<td>0.308</td>
<td>0.327</td>
<td>0.245</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td>Confidence Interval</td>
<td>0.204 : 0.265</td>
<td>0.265 : 0.351</td>
<td>0.283 : 0.372</td>
<td>0.208 : 0.282</td>
<td style="text-align: right;">0.223 : 0.296</td>
</tr>
<tr class="odd">
<td>Heterogeneity tau</td>
<td>0.049</td>
<td>0.08</td>
<td>0.083</td>
<td>0.069</td>
<td style="text-align: right;">0.068</td>
</tr>
<tr class="even">
<td>Heteroeneity I^2</td>
<td>52.902</td>
<td>72.703</td>
<td>72.339</td>
<td>76.582</td>
<td style="text-align: right;">74.663</td>
</tr>
<tr class="odd">
<td>Heterogeneity H^2</td>
<td>2.123</td>
<td>3.663</td>
<td>3.615</td>
<td>4.27</td>
<td style="text-align: right;">3.947</td>
</tr>
<tr class="even">
<td>Q(18)</td>
<td>39.551</td>
<td>90.652</td>
<td>64.645</td>
<td>120.464</td>
<td style="text-align: right;">80.405</td>
</tr>
<tr class="odd">
<td>P-value QE</td>
<td>0.002</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td style="text-align: right;">&lt;.001</td>
</tr>
</tbody>
</table>
</section>
<section id="error-score-variance" class="level4">
<h4 class="anchored" data-anchor-id="error-score-variance">Error Score Variance</h4>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>HH</th>
<th>EM</th>
<th>EX</th>
<th>AG</th>
<th style="text-align: right;">CO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Min</td>
<td>0.085</td>
<td>0.086</td>
<td>0.071</td>
<td>0.079</td>
<td style="text-align: right;">0.074</td>
</tr>
<tr class="even">
<td>Q1</td>
<td>0.095</td>
<td>0.092</td>
<td>0.075</td>
<td>0.085</td>
<td style="text-align: right;">0.078</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>0.104</td>
<td>0.095</td>
<td>0.081</td>
<td>0.09</td>
<td style="text-align: right;">0.084</td>
</tr>
<tr class="even">
<td>Q3</td>
<td>0.102</td>
<td>0.097</td>
<td>0.084</td>
<td>0.092</td>
<td style="text-align: right;">0.086</td>
</tr>
<tr class="odd">
<td>Max</td>
<td>0.108</td>
<td>0.102</td>
<td>0.094</td>
<td>0.096</td>
<td style="text-align: right;">0.089</td>
</tr>
<tr class="even">
<td>Mean</td>
<td>0.12</td>
<td>0.114</td>
<td>0.104</td>
<td>0.112</td>
<td style="text-align: right;">0.117</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>HH</th>
<th>EM</th>
<th>EX</th>
<th>AG</th>
<th style="text-align: right;">CO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Meta-analytic mean estimate</td>
<td>0.102</td>
<td>0.097</td>
<td>0.083</td>
<td>0.092</td>
<td style="text-align: right;">0.085</td>
</tr>
<tr class="even">
<td>Confidence Interval</td>
<td>0.097 : 0.106</td>
<td>0.093 : 0.1</td>
<td>0.078 : 0.088</td>
<td>0.088 : 0.095</td>
<td style="text-align: right;">0.081 : 0.09</td>
</tr>
<tr class="odd">
<td>Heterogeneity tau</td>
<td>0.008</td>
<td>0.005</td>
<td>0.009</td>
<td>0.007</td>
<td style="text-align: right;">0.009</td>
</tr>
<tr class="even">
<td>Heteroeneity I^2</td>
<td>69.422</td>
<td>49.982</td>
<td>80.355</td>
<td>65.765</td>
<td style="text-align: right;">77.466</td>
</tr>
<tr class="odd">
<td>Heterogeneity H^2</td>
<td>3.27</td>
<td>1.999</td>
<td>5.09</td>
<td>2.921</td>
<td style="text-align: right;">4.438</td>
</tr>
<tr class="even">
<td>Q(18)</td>
<td>59.251</td>
<td>35.907</td>
<td>80.68</td>
<td>50.173</td>
<td style="text-align: right;">68.688</td>
</tr>
<tr class="odd">
<td>P-value QE</td>
<td>&lt;.001</td>
<td>0.007</td>
<td>&lt;.001</td>
<td>&lt;.001</td>
<td style="text-align: right;">&lt;.001</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'tidyverse' wurde unter R Version 4.2.2 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.2     ✔ purrr   1.0.1
✔ tibble  3.2.1     ✔ dplyr   1.1.1
✔ tidyr   1.3.0     ✔ stringr 1.5.0
✔ readr   2.1.4     ✔ forcats 1.0.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'ggplot2' wurde unter R Version 4.2.3 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'tibble' wurde unter R Version 4.2.3 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'tidyr' wurde unter R Version 4.2.2 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'readr' wurde unter R Version 4.2.3 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'purrr' wurde unter R Version 4.2.2 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'dplyr' wurde unter R Version 4.2.3 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'stringr' wurde unter R Version 4.2.2 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Paket 'forcats' wurde unter R Version 4.2.2 erstellt</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Simulation Results</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>vis.df_empF <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">file.path</span>(<span class="st">"Notes/vis_df.csv"</span>), <span class="at">sep =</span> <span class="st">" "</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>vis.df_empT <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">file.path</span>(<span class="st">"Notes/vis_df_empT.csv"</span>), <span class="at">sep =</span> <span class="st">" "</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>vis.df_summarised_empF <span class="ot">&lt;-</span> vis.df_empF <span class="sc">%&gt;%</span> </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CVT, CVE, rel) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">T_m =</span> <span class="fu">mean</span>(tau_T, <span class="at">na.rm =</span> T),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_m =</span> <span class="fu">mean</span>(tau_E, <span class="at">na.rm =</span> T),</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">T_sd =</span> <span class="fu">sd</span>(tau_T, <span class="at">na.rm =</span> T),</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_sd =</span> <span class="fu">sd</span>(tau_E, <span class="at">na.rm =</span> T),</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">T_ll =</span> <span class="fu">quantile</span>(tau_T, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">T_ul =</span> <span class="fu">quantile</span>(tau_T, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_ll =</span> <span class="fu">quantile</span>(tau_E, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_ul =</span> <span class="fu">quantile</span>(tau_E, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.MAE_m =</span> <span class="fu">mean</span>(varT.MAE, <span class="at">na.rm =</span> T),</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.MAE_m =</span> <span class="fu">mean</span>(varE.MAE, <span class="at">na.rm =</span> T),</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.MAE_ll =</span> <span class="fu">quantile</span>(varT.MAE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.MAE_ul =</span> <span class="fu">quantile</span>(varT.MAE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.MAE_ll =</span> <span class="fu">quantile</span>(varE.MAE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.MAE_ul =</span> <span class="fu">quantile</span>(varE.MAE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.M_m =</span> <span class="fu">mean</span>(varT.M, <span class="at">na.rm =</span> T),</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.M_m =</span> <span class="fu">mean</span>(varE.M, <span class="at">na.rm =</span> T),</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.M_ll =</span> <span class="fu">quantile</span>(varT.M, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.M_ul =</span> <span class="fu">quantile</span>(varT.M, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.M_ll =</span> <span class="fu">quantile</span>(varE.M, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.M_ul =</span> <span class="fu">quantile</span>(varE.M, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.M_m =</span> <span class="fu">mean</span>(rel.M, <span class="at">na.rm =</span> T),</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.M_ll =</span> <span class="fu">quantile</span>(rel.M, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.M_ul =</span> <span class="fu">quantile</span>(rel.M, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.MAE_m =</span> <span class="fu">mean</span>(rel.MAE, <span class="at">na.rm =</span> T),</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.MAE_ll =</span> <span class="fu">quantile</span>(rel.MAE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.MAE_ul =</span> <span class="fu">quantile</span>(rel.MAE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_m =</span> <span class="fu">mean</span>(tau_rel, <span class="at">na.rm =</span> T),</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_ll =</span> <span class="fu">quantile</span>(tau_rel, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_ul =</span> <span class="fu">quantile</span>(tau_rel, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cT_m =</span> <span class="fu">mean</span>(tau_rel_cT, <span class="at">na.rm =</span> T),</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cT_ll =</span> <span class="fu">quantile</span>(tau_rel_cT, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cT_ul =</span> <span class="fu">quantile</span>(tau_rel_cT, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cE_m =</span> <span class="fu">mean</span>(tau_rel_cE, <span class="at">na.rm =</span> T),</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cE_ll =</span> <span class="fu">quantile</span>(tau_rel_cE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cE_ul =</span> <span class="fu">quantile</span>(tau_rel_cE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cTE_m =</span> <span class="fu">mean</span>(tau_rel_cTE, <span class="at">na.rm =</span> T),</span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cTE_ll =</span> <span class="fu">quantile</span>(tau_rel_cTE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cTE_ul =</span> <span class="fu">quantile</span>(tau_rel_cTE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'CVT', 'CVE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>vis.df_summarised_empT <span class="ot">&lt;-</span> vis.df_empT <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CVT, CVE, rel) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">T_m =</span> <span class="fu">mean</span>(tau_T, <span class="at">na.rm =</span> T),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_m =</span> <span class="fu">mean</span>(tau_E, <span class="at">na.rm =</span> T),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">T_sd =</span> <span class="fu">sd</span>(tau_T, <span class="at">na.rm =</span> T),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_sd =</span> <span class="fu">sd</span>(tau_E, <span class="at">na.rm =</span> T),</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">T_ll =</span> <span class="fu">quantile</span>(tau_T, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">T_ul =</span> <span class="fu">quantile</span>(tau_T, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_ll =</span> <span class="fu">quantile</span>(tau_E, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">E_ul =</span> <span class="fu">quantile</span>(tau_E, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.MAE_m =</span> <span class="fu">mean</span>(varT.MAE, <span class="at">na.rm =</span> T),</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.MAE_m =</span> <span class="fu">mean</span>(varE.MAE, <span class="at">na.rm =</span> T),</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.MAE_ll =</span> <span class="fu">quantile</span>(varT.MAE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.MAE_ul =</span> <span class="fu">quantile</span>(varT.MAE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.MAE_ll =</span> <span class="fu">quantile</span>(varE.MAE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.MAE_ul =</span> <span class="fu">quantile</span>(varE.MAE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.M_m =</span> <span class="fu">mean</span>(varT.M, <span class="at">na.rm =</span> T),</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.M_m =</span> <span class="fu">mean</span>(varE.M, <span class="at">na.rm =</span> T),</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.M_ll =</span> <span class="fu">quantile</span>(varT.M, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">VT.M_ul =</span> <span class="fu">quantile</span>(varT.M, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.M_ll =</span> <span class="fu">quantile</span>(varE.M, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">VE.M_ul =</span> <span class="fu">quantile</span>(varE.M, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.M_m =</span> <span class="fu">mean</span>(rel.M, <span class="at">na.rm =</span> T),</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.M_ll =</span> <span class="fu">quantile</span>(rel.M, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.M_ul =</span> <span class="fu">quantile</span>(rel.M, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.MAE_m =</span> <span class="fu">mean</span>(rel.MAE, <span class="at">na.rm =</span> T),</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.MAE_ll =</span> <span class="fu">quantile</span>(rel.MAE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>            <span class="at">rel.MAE_ul =</span> <span class="fu">quantile</span>(rel.MAE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_m =</span> <span class="fu">mean</span>(tau_rel, <span class="at">na.rm =</span> T),</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_ll =</span> <span class="fu">quantile</span>(tau_rel, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_ul =</span> <span class="fu">quantile</span>(tau_rel, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cT_m =</span> <span class="fu">mean</span>(tau_rel_cT, <span class="at">na.rm =</span> T),</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cT_ll =</span> <span class="fu">quantile</span>(tau_rel_cT, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cT_ul =</span> <span class="fu">quantile</span>(tau_rel_cT, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cE_m =</span> <span class="fu">mean</span>(tau_rel_cE, <span class="at">na.rm =</span> T),</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cE_ll =</span> <span class="fu">quantile</span>(tau_rel_cE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cE_ul =</span> <span class="fu">quantile</span>(tau_rel_cE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cTE_m =</span> <span class="fu">mean</span>(tau_rel_cTE, <span class="at">na.rm =</span> T),</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cTE_ll =</span> <span class="fu">quantile</span>(tau_rel_cTE, .<span class="dv">025</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>            <span class="at">tau_rel_cTE_ul =</span> <span class="fu">quantile</span>(tau_rel_cTE, .<span class="dv">975</span>, <span class="at">na.rm =</span> T))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'CVT', 'CVE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>vis.df_summarized2_empF <span class="ot">&lt;-</span> vis.df_empF <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CVT, CVE, rel) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">bias_varT.M =</span> <span class="fu">mean</span>(varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_varT.MAE =</span> <span class="fu">mean</span>(varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_varE.M =</span> <span class="fu">mean</span>(varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_varE.MAE =</span> <span class="fu">mean</span>(varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_rel.M =</span> <span class="fu">mean</span>(rel.M <span class="sc">-</span> rel, <span class="at">na.rm =</span> T),</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_rel.MAE =</span> <span class="fu">mean</span>(rel.MAE<span class="sc">-</span>rel, <span class="at">na.rm =</span> T),</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_tauT =</span> <span class="fu">mean</span>(tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_tauE =</span> <span class="fu">mean</span>(tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varT.M =</span> <span class="fu">mean</span>((varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varT.MAE =</span> <span class="fu">mean</span>((varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varE.M =</span> <span class="fu">mean</span>((varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varE.MAE =</span> <span class="fu">mean</span>((varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_rel.M =</span> <span class="fu">mean</span>((rel.M <span class="sc">-</span> rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_rel.MAE =</span> <span class="fu">mean</span>((rel.MAE<span class="sc">-</span>rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_tauT =</span> <span class="fu">mean</span>((tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_tauE =</span> <span class="fu">mean</span>((tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varT.M =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varT.MAE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varE.M =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varE.MAE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_rel.M =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((rel.M <span class="sc">-</span> rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_rel.MAE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((rel.MAE<span class="sc">-</span>rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_tauT =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_tauE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'CVT', 'CVE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>vis.df_summarized2_empT <span class="ot">&lt;-</span> vis.df_empT <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(CVT, CVE, rel) <span class="sc">%&gt;%</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">bias_varT.M =</span> <span class="fu">mean</span>(varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_varT.MAE =</span> <span class="fu">mean</span>(varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_varE.M =</span> <span class="fu">mean</span>(varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_varE.MAE =</span> <span class="fu">mean</span>(varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_rel.M =</span> <span class="fu">mean</span>(rel.M <span class="sc">-</span> rel, <span class="at">na.rm =</span> T),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_rel.MAE =</span> <span class="fu">mean</span>(rel.MAE<span class="sc">-</span>rel, <span class="at">na.rm =</span> T),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_tauT =</span> <span class="fu">mean</span>(tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">bias_tauE =</span> <span class="fu">mean</span>(tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varT.M =</span> <span class="fu">mean</span>((varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varT.MAE =</span> <span class="fu">mean</span>((varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varE.M =</span> <span class="fu">mean</span>((varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_varE.MAE =</span> <span class="fu">mean</span>((varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_rel.M =</span> <span class="fu">mean</span>((rel.M <span class="sc">-</span> rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_rel.MAE =</span> <span class="fu">mean</span>((rel.MAE<span class="sc">-</span>rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_tauT =</span> <span class="fu">mean</span>((tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T),</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">MSE_tauE =</span> <span class="fu">mean</span>((tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>), <span class="at">na.rm =</span> T)<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varT.M =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varT.MAE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varE.M =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_varE.MAE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_rel.M =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((rel.M <span class="sc">-</span> rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_rel.MAE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((rel.MAE<span class="sc">-</span>rel)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_tauT =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span>, <span class="at">na.rm =</span> T)),</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a>            <span class="at">RMSE_tauE =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>), <span class="at">na.rm =</span> T)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>            )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'CVT', 'CVE'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>vis.df2_empF <span class="ot">&lt;-</span> vis.df_empF <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bias_varT.M =</span> (varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_varT.MAE =</span> (varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_varE.M =</span> (varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_varE.MAE =</span> (varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_rel.M =</span> (rel.M <span class="sc">-</span> rel),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_rel.MAE =</span> (rel.MAE<span class="sc">-</span>rel),</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_tauT =</span> (tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_tauE =</span> (tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>vis.df2_empT <span class="ot">&lt;-</span> vis.df_empT <span class="sc">%&gt;%</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bias_varT.M =</span> (varT.M <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_varT.MAE =</span> (varT.MAE <span class="sc">-</span> rel<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_varE.M =</span> (varE.M <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_varE.MAE =</span> (varE.MAE <span class="sc">-</span> (<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_rel.M =</span> (rel.M <span class="sc">-</span> rel),</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_rel.MAE =</span> (rel.MAE<span class="sc">-</span>rel),</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_tauT =</span> (tau_T <span class="sc">-</span> CVT<span class="sc">*</span>rel<span class="sc">*</span><span class="dv">10</span>),</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_tauE =</span> (tau_E <span class="sc">-</span> CVE<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>rel)<span class="sc">*</span><span class="dv">10</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vis.df_empT) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">colnames</span>(vis.df_empF), <span class="st">"_empT"</span>)</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vis.df_summarised_empT) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">colnames</span>(vis.df_summarised_empF), <span class="st">"_empT"</span>)</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vis.df_summarized2_empT) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">colnames</span>(vis.df_summarized2_empF), <span class="st">"_empT"</span>)</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vis.df2_empT) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="fu">colnames</span>(vis.df2_empF), <span class="st">"_empT"</span>)</span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>vis.df <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vis.df_empF, vis.df_empT)</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>vis.df_summarised <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vis.df_summarised_empF, vis.df_summarised_empT)</span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>vis.df_summarized2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vis.df_summarized2_empF, vis.df_summarized2_empT)</span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>vis.df2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vis.df2_empF, vis.df2_empT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>vis.df_summarized2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 54
# Groups:   CVT, CVE [16]
     CVT   CVE   rel bias_varT.M bias_varT.MAE bias_varE.M bias_varE.MAE
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;
 1     0   0     0.1    0.00215         -0.297   -0.00207       -0.0376 
 2     0   0     0.3    0.000652        -0.310   -0.00273       -0.0303 
 3     0   0     0.5   -0.000509        -0.319    0.000297      -0.0198 
 4     0   0     0.7    0.00310         -0.320   -0.000659      -0.0127 
 5     0   0     0.9    0.00682         -0.324    0.000102      -0.00388
 6     0   0.1   0.1    0.00808         -0.295    0.00388       -0.0347 
 7     0   0.1   0.3    0.00338         -0.307   -0.00429       -0.0343 
 8     0   0.1   0.5    0.0104          -0.309   -0.00410       -0.0256 
 9     0   0.1   0.7   -0.00419         -0.329    0.00393       -0.00902
10     0   0.1   0.9    0.00516         -0.321   -0.000591      -0.00484
# ℹ 70 more rows
# ℹ 47 more variables: bias_rel.M &lt;dbl&gt;, bias_rel.MAE &lt;dbl&gt;, bias_tauT &lt;dbl&gt;,
#   bias_tauE &lt;dbl&gt;, MSE_varT.M &lt;dbl&gt;, MSE_varT.MAE &lt;dbl&gt;, MSE_varE.M &lt;dbl&gt;,
#   MSE_varE.MAE &lt;dbl&gt;, MSE_rel.M &lt;dbl&gt;, MSE_rel.MAE &lt;dbl&gt;, MSE_tauT &lt;dbl&gt;,
#   MSE_tauE &lt;dbl&gt;, RMSE_varT.M &lt;dbl&gt;, RMSE_varT.MAE &lt;dbl&gt;, RMSE_varE.M &lt;dbl&gt;,
#   RMSE_varE.MAE &lt;dbl&gt;, RMSE_rel.M &lt;dbl&gt;, RMSE_rel.MAE &lt;dbl&gt;, RMSE_tauT &lt;dbl&gt;,
#   RMSE_tauE &lt;dbl&gt;, CVT_empT &lt;dbl&gt;, CVE_empT &lt;dbl&gt;, rel_empT &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>vis.df_summarised<span class="sc">$</span>T_ul <span class="sc">-</span> vis.df_summarised<span class="sc">$</span>T_ll</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.9980080 0.9481348 0.9496716 0.9469212 0.9712860 0.9618731 0.9528763 0.9408710 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.9307054 0.9715433 0.8815830 0.9289250 0.9236190 0.9636163 0.9582408 0.8610613 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.8787312 0.9381103 0.9585010 0.9998592 0.9869175 0.9833532 1.0263499 0.7860384 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.7152636 0.9431323 0.9779654 1.1092559 0.7585112 0.7422973 0.9010322 0.9817085 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
1.0573597 0.7943605 0.7775251 0.8949700 0.9555611 1.0536290 0.8316046 0.7892287 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.9889657 1.1077520 0.7923271 0.7063435 0.7363034 0.9838759 0.9989508 0.7463248 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.7129990 0.6933129 0.9283158 1.0862069 0.7878726 0.7488063 0.7027118 0.8529257 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.8535446 0.7353154 0.7555984 0.7592874 1.0226183 0.8562861 0.6868790 0.7970994 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.8772766 0.9955845 0.8128083 0.6934829 0.7643218 0.8783175 0.9743909 0.8176535 
    97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5%     97.5% 
0.7294808 0.7782159 0.9569009 0.9011559 0.6824830 0.7433174 0.7051011 0.8995885 </code></pre>
</div>
</div>
<p>Simulating data under seemingly ideal circumstances – normal distribution of random true and error score variances, tau-equivalence of scores , …? – has shown that an analysis of score variance components is not without its flaws.</p>
<p>Concerning the heterogeneity in true score variance, the simulation demonstrates that degrees of uncertainty remain, surrounding the estimates of heterogeneity. In total, the size of confidence intervals varied between 0.682 and 1.109. Across conditions, RMSE varied between 0.182 and 0.604. As demonstrated in figure X, these seem positively related to the degree of score reliability. However, even at the highest level of reliability, uncertainty in estimated true score variance heterogeneity remained between 0.693 and 1. In terms of RMSE, uncertainty in estimated true score variance hetergeneity remained between 0.186 and 0.604 at score reliability of .9. Uncertainty is also related to the degree of true score variance heterogeneity, at higher degrees of heterogeneity the uncertainty seems to fall. For example, at score reliability of .7, average confidence interval size falls from 0.95 at CV_T of 0, to 0.761 at CV_T of .3. Similarly, at score reliability of .7, mean RMSE falls from 0.585 at CV_T of 0, to 0.216 at CV_T of .3.</p>
<p>More importantly, heterogeneity in true score variance estimates is highly overestimated at low degrees of reliability and low degrees of simulated heterogeneity. Average bias across all conditions was 0.188. In figure X, we can see that this overestimation falls with increasing heterogeneity in true score variance, as well as larger degree of score reliability. For example, at a reliability of .7, we see that average bias in heterogeneity in true score variance drops from 0.519 at CV_T = 0, to -0.082 at CV_T = .3. If anything, we seem to observe some degree of underestimation of heterogeneity in true score variance, if reliability is larger than .5 and heterogeneity is large. On the other hand, the simulated heterogeneity in error score variances seems to have no obvious effect on the estimates of true score variance heterogeneity.</p>
<p>Compared to the estimation of heterogeneity in true score variance, estimation of error score variance heterogeneity is more precise and accurate. The size of confidence intervals varied more strongly between 0.028 and 0.727, see figure X. Similarly, across all conditions, RMSE varied between 0.008 and 0.194. Overall, it appears estimation was more precise at all levels of score reliability and degree of heterogeneity. Similarly to true score variance, for error score variance heterogeneity, we observed that its uncertainty in estimation fell an increase in score reliability. For example, average confidence interval size drops from 0.451 at score reliability of .1, to 0.05 at score reliability of .9. Similary, mean RMSE drops from 0.135 to 0.015, as score reliability rises from .1 to .9. At the same time, uncertainty in the esimtation of error score variance heterogeneity rises, as heterogeneity grows, across all levels of score reliability. For example, at score reliability of .7, average confidence interval size rises from 0.089 at CV_E of 0, to 0.242 at CV_E of .3. Similarly, at score reliability of .7, mean RMSE rises from 0.046 at CV_E of 0, to 0.065 at CV_E of .3. Concerning the relationship between score variance heterogeneity in uncertainty in its estimation, it appears that relationship is inverse for error score variance, compared to true score variance. While estimation of true score variance heterogeneity gets more precise as heterogeneity rises, estimation of error score variance gets more imprecise.</p>
<p>While we observed some overestimation in true score variance heterogeneity, we seem to find less so for error score variance heterogeneity. On average, across all conditions, bias was 0.188. When score reliability and error score variance heterogeneity is low, from figure X it become clear that we still find some overestimation. For example, at a reliability of .7, we see that average bias in heterogeneity in error score variance drops from 0.035 at CV_E = 0, to -0.018 at CV_T = .3. While over- and underestimation of error score variance heterogeneity follows the same pattern as that of true score variance heterogeneity, from a comparison of figures X and X, it becomes clear that this pattern is less strongly pronounced for heterogeneity in error score variance.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>